name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Add wasm32-unknown-unknown target
        run: rustup target add wasm32-unknown-unknown
   
      - name: Build the project
        run: cargo build --target wasm32-unknown-unknown --release

      - name: Prepare deployment directory
        run: |
          mkdir -p public
          cp target/wasm32-unknown-unknown/release/DayVsNight.wasm public/
          cp index.html public/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
